idris_sim:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Steering Controllers ---------------------------------------
  front_right_steering_controller:
    type: position_controllers/JointPositionController
#    type: effort_controllers/JointEffortController
    joint: chassis_to_front_right_axle_joint
    pid: {p: 100.0, i: 0.02, d: 0.2}

  front_left_steering_controller:
    type: position_controllers/JointPositionController
#    type: effort_controllers/JointEffortController
    joint: chassis_to_front_left_axle_joint
    pid: {p: 100.0, i: 0.02, d: 0.2}

  rear_right_steering_controller:
    type: position_controllers/JointPositionController
#    type: effort_controllers/JointEffortController
    joint: chassis_to_rear_right_axle_joint
    pid: {p: 100.0, i: 0.02, d: 0.2}

  rear_left_steering_controller:
    type: position_controllers/JointPositionController
#    type: effort_controllers/JointEffortController
    joint: chassis_to_rear_left_axle_joint
    pid: {p: 100.0, i: 0.02, d: 0.2}

  # Speed controllers.
  front_right_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_right_axle_to_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 0.1}

  front_left_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: front_left_axle_to_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 0.1}

  rear_right_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: rear_right_axle_to_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 0.1}

  rear_left_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: rear_left_axle_to_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 0.1}
