# CMake generated Testfile for 
# Source directory: /home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/tests
# Build directory: /home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_mrpt_comms_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_comms")
add_test(test_mrpt_comms_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_comms")
set_tests_properties(test_mrpt_comms_run PROPERTIES  DEPENDS "test_mrpt_comms_build")
add_test(test_mrpt_config_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_config")
add_test(test_mrpt_config_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_config")
set_tests_properties(test_mrpt_config_run PROPERTIES  DEPENDS "test_mrpt_config_build")
add_test(test_mrpt_containers_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_containers")
add_test(test_mrpt_containers_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_containers")
set_tests_properties(test_mrpt_containers_run PROPERTIES  DEPENDS "test_mrpt_containers_build")
add_test(test_mrpt_core_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_core")
add_test(test_mrpt_core_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_core")
set_tests_properties(test_mrpt_core_run PROPERTIES  DEPENDS "test_mrpt_core_build")
add_test(test_mrpt_db_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_db")
add_test(test_mrpt_db_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_db")
set_tests_properties(test_mrpt_db_run PROPERTIES  DEPENDS "test_mrpt_db_build")
add_test(test_mrpt_expr_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_expr")
add_test(test_mrpt_expr_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_expr")
set_tests_properties(test_mrpt_expr_run PROPERTIES  DEPENDS "test_mrpt_expr_build")
add_test(test_mrpt_graphs_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_graphs")
add_test(test_mrpt_graphs_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_graphs")
set_tests_properties(test_mrpt_graphs_run PROPERTIES  DEPENDS "test_mrpt_graphs_build")
add_test(test_mrpt_graphslam_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_graphslam")
add_test(test_mrpt_graphslam_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_graphslam")
set_tests_properties(test_mrpt_graphslam_run PROPERTIES  DEPENDS "test_mrpt_graphslam_build")
add_test(test_mrpt_hwdrivers_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_hwdrivers")
add_test(test_mrpt_hwdrivers_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_hwdrivers")
set_tests_properties(test_mrpt_hwdrivers_run PROPERTIES  DEPENDS "test_mrpt_hwdrivers_build")
add_test(test_mrpt_img_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_img")
add_test(test_mrpt_img_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_img")
set_tests_properties(test_mrpt_img_run PROPERTIES  DEPENDS "test_mrpt_img_build")
add_test(test_mrpt_io_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_io")
add_test(test_mrpt_io_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_io")
set_tests_properties(test_mrpt_io_run PROPERTIES  DEPENDS "test_mrpt_io_build")
add_test(test_mrpt_maps_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_maps")
add_test(test_mrpt_maps_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_maps")
set_tests_properties(test_mrpt_maps_run PROPERTIES  DEPENDS "test_mrpt_maps_build")
add_test(test_mrpt_math_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_math")
add_test(test_mrpt_math_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_math")
set_tests_properties(test_mrpt_math_run PROPERTIES  DEPENDS "test_mrpt_math_build")
add_test(test_mrpt_nanoflann_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_nanoflann")
add_test(test_mrpt_nanoflann_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_nanoflann")
set_tests_properties(test_mrpt_nanoflann_run PROPERTIES  DEPENDS "test_mrpt_nanoflann_build")
add_test(test_mrpt_nav_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_nav")
add_test(test_mrpt_nav_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_nav")
set_tests_properties(test_mrpt_nav_run PROPERTIES  DEPENDS "test_mrpt_nav_build")
add_test(test_mrpt_obs_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_obs")
add_test(test_mrpt_obs_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_obs")
set_tests_properties(test_mrpt_obs_run PROPERTIES  DEPENDS "test_mrpt_obs_build")
add_test(test_mrpt_opengl_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_opengl")
add_test(test_mrpt_opengl_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_opengl")
set_tests_properties(test_mrpt_opengl_run PROPERTIES  DEPENDS "test_mrpt_opengl_build")
add_test(test_mrpt_poses_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_poses")
add_test(test_mrpt_poses_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_poses")
set_tests_properties(test_mrpt_poses_run PROPERTIES  DEPENDS "test_mrpt_poses_build")
add_test(test_mrpt_random_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_random")
add_test(test_mrpt_random_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_random")
set_tests_properties(test_mrpt_random_run PROPERTIES  DEPENDS "test_mrpt_random_build")
add_test(test_mrpt_rtti_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_rtti")
add_test(test_mrpt_rtti_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_rtti")
set_tests_properties(test_mrpt_rtti_run PROPERTIES  DEPENDS "test_mrpt_rtti_build")
add_test(test_mrpt_serialization_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_serialization")
add_test(test_mrpt_serialization_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_serialization")
set_tests_properties(test_mrpt_serialization_run PROPERTIES  DEPENDS "test_mrpt_serialization_build")
add_test(test_mrpt_slam_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_slam")
add_test(test_mrpt_slam_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_slam")
set_tests_properties(test_mrpt_slam_run PROPERTIES  DEPENDS "test_mrpt_slam_build")
add_test(test_mrpt_system_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_system")
add_test(test_mrpt_system_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_system")
set_tests_properties(test_mrpt_system_run PROPERTIES  DEPENDS "test_mrpt_system_build")
add_test(test_mrpt_tfest_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_tfest")
add_test(test_mrpt_tfest_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_tfest")
set_tests_properties(test_mrpt_tfest_run PROPERTIES  DEPENDS "test_mrpt_tfest_build")
add_test(test_mrpt_topography_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_topography")
add_test(test_mrpt_topography_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_topography")
set_tests_properties(test_mrpt_topography_run PROPERTIES  DEPENDS "test_mrpt_topography_build")
add_test(test_mrpt_typemeta_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_typemeta")
add_test(test_mrpt_typemeta_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_typemeta")
set_tests_properties(test_mrpt_typemeta_run PROPERTIES  DEPENDS "test_mrpt_typemeta_build")
add_test(test_mrpt_vision_build "/usr/bin/cmake" "--build" "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt" "--target" "test_mrpt_vision")
add_test(test_mrpt_vision_run "/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/bin/test_mrpt_vision")
set_tests_properties(test_mrpt_vision_run PROPERTIES  DEPENDS "test_mrpt_vision_build")
