# Install script for directory: /home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/2d-slam-demo/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/DifOdometry-Camera/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/DifOdometry-Datasets/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/GridmapNavSimul/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/RawLogViewer/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/ReactiveNav3D-Demo/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/ReactiveNavigationDemo/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/SceneViewer3D/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/benchmarking-image-features/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/camera-calib/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/carmen2rawlog/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/carmen2simplemap/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/common/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/features-matching/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/gps2rawlog/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/graph-slam/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/graphslam-engine/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/grid-matching/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/hmt-slam/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/hmt-slam-gui/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/hmtMapViewer/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/holonomic-navigator-demo/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/icp-slam/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/icp-slam-live/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/image2gridmap/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/kf-slam/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/kinect-3d-slam/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/kinect-3d-view/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/kinect-stereo-calib/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/map-partition/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/mrpt-performance/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/navlog-viewer/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/observations2map/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/pf-localization/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/ptg-configurator/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/rawlog-edit/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/rawlog-grabber/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/rbpf-slam/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/ro-localization/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/robot-map-gui/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/robotic-arm-kinematics/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/simul-beacons/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/simul-gridmap/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/simul-landmarks/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/track-video-features/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/velodyne-view/cmake_install.cmake")
  include("/home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps/wx-common/cmake_install.cmake")

endif()

