#ifndef CVD_INCLUDE_CONFIG_H_3216ac8
#define CVD_INCLUDE_CONFIG_H_3216ac8
/* #undef CVD_VERSION_STRING */
/* #undef CVD_HAVE_TOON */
#define CVD_HAVE_JPEG
#define CVD_HAVE_PNG
#define CVD_HAVE_TIFF
#define CVD_HAVE_GLOB
#endif
