# CMake generated Testfile for 
# Source directory: /home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps
# Build directory: /home/matt/Documents/Robot-transporting/workspace/src/van_loading/libs/mrpt/apps
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("2d-slam-demo")
subdirs("DifOdometry-Camera")
subdirs("DifOdometry-Datasets")
subdirs("GridmapNavSimul")
subdirs("RawLogViewer")
subdirs("ReactiveNav3D-Demo")
subdirs("ReactiveNavigationDemo")
subdirs("SceneViewer3D")
subdirs("benchmarking-image-features")
subdirs("camera-calib")
subdirs("carmen2rawlog")
subdirs("carmen2simplemap")
subdirs("common")
subdirs("features-matching")
subdirs("gps2rawlog")
subdirs("graph-slam")
subdirs("graphslam-engine")
subdirs("grid-matching")
subdirs("hmt-slam")
subdirs("hmt-slam-gui")
subdirs("hmtMapViewer")
subdirs("holonomic-navigator-demo")
subdirs("icp-slam")
subdirs("icp-slam-live")
subdirs("image2gridmap")
subdirs("kf-slam")
subdirs("kinect-3d-slam")
subdirs("kinect-3d-view")
subdirs("kinect-stereo-calib")
subdirs("map-partition")
subdirs("mrpt-performance")
subdirs("navlog-viewer")
subdirs("observations2map")
subdirs("pf-localization")
subdirs("ptg-configurator")
subdirs("rawlog-edit")
subdirs("rawlog-grabber")
subdirs("rbpf-slam")
subdirs("ro-localization")
subdirs("robot-map-gui")
subdirs("robotic-arm-kinematics")
subdirs("simul-beacons")
subdirs("simul-gridmap")
subdirs("simul-landmarks")
subdirs("track-video-features")
subdirs("velodyne-view")
subdirs("wx-common")
